# ==============================================================================
# snm-mqtt.conf
# Reto ACME Let's Encrypt en HTTP (puerto 80) para el subdominio de MQTT
# Marcador de plantilla: mqtt.mesh.example.org -> reemplazado por mqtt.${PROJECT_DOMAIN}
# ==============================================================================

server {
    listen 80;
    listen [::]:80;
    server_name mqtt.mesh.example.org;

    # Validación ACME HTTP-01 de Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        try_files $uri =404;
    }

    location / {
        default_type text/plain;
        return 404 "Andalucía Mesh: El servicio MQTT está disponible en los puertos 1883 (plano) y 8883 (TLS).\n";
    }
}
