"""Metadatos estáticos y catálogo completo de reglas de supervisión."""

from typing import Any

METADATOS_REGLAS: dict[str, dict[str, Any]] = {
    # --- Reglas de Supervisión Activas ---
    "reboot-loop": {
        "nombre": "Bucle de reinicio",
        "descripcion": "Detección de reinicios continuos (3 en 5 min medio, ≥ 5 en 10 min alerta roja)",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "battery-low": {
        "nombre": "Batería baja",
        "descripcion": "Nivel de batería crítico en muestras consecutivas (routers < 60% med / < 40% alto; clientes < 35% bajo / < 15% med)",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["bajo", "medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "chutil-high": {
        "nombre": "Canal saturado",
        "descripcion": "Ocupación de canal LoRa excesiva (> 20% bajo, > 30% medio, > 40% alto; 60% routers, 40% clientes)",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["bajo", "medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "text-flood": {
        "nombre": "Ráfaga de mensajes de texto",
        "descripcion": "Emisión excesiva de mensajes de texto en 1 min (> 5 bajo, 6-10 medio, > 10 alto)",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["bajo", "medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "telemetry-burst": {
        "nombre": "Ráfaga de telemetría",
        "descripcion": "Emisiones repetidas de telemetría o nodeinfo (≥ 2 en 1 min bajo, > 50/h alto; ráfagas combinadas y constantes)",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["bajo", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "poll-abuse": {
        "nombre": "Abuso de sondeos broadcast",
        "descripcion": "Sondeos indiscriminados a broadcast (^all) que provocan respuestas masivas (1 bajo, ≥ 3 medio, ≥ 5 alto)",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["bajo", "medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "sunset-battery": {
        "nombre": "Batería crítica al anochecer",
        "descripcion": "Router solar en Andalucía con batería < 60% a las 20:00 h peninsulares sin carga solar nocturna",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura"],
    },
    "traceroute-flood": {
        "nombre": "Abuso de traceroutes",
        "descripcion": "Emisión excesiva de traceroutes en 30 min (10-19 medio, ≥ 20 alto)",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "private-chaff": {
        "nombre": "Tráfico cifrado privado en malla pública",
        "descripcion": "Paquetes privados o de sensores saturando repetidamente la red LoRa pública",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "position-flood": {
        "nombre": "Posicionamiento hiperactivo",
        "descripcion": "Cadencia excesiva de balizas de posición (≥ 4 en 5m bajo, ≥ 8 en 10m medio, ≥ 20 en 15m alto)",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["bajo", "medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "router-role": {
        "nombre": "Router no coordinado",
        "descripcion": "Nodo con rol ROUTER en Andalucía sin coordinación previa con la comunidad",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "infra-silent": {
        "nombre": "Router silente",
        "descripcion": "Router de infraestructura que deja de oírse según su intervalo típico",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura"],
    },
    "gateway-offline": {
        "nombre": "Gateway desconectado",
        "descripcion": "Pasarela que deja de publicar recepciones en el broker MQTT",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura"],
    },
    "flood": {
        "nombre": "Inundación de paquetes",
        "descripcion": "Nodo emitiendo tráfico propio por encima de su ritmo normal",
        "fase": "mvp",
        "afecta_malla": True,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura"],
    },
    "rafaga-masiva": {
        "nombre": "Ráfaga masiva simultánea",
        "descripcion": "Múltiples nodos emitiendo de forma sincronizada en la malla",
        "fase": "mvp",
        "afecta_malla": True,
        "riesgos": ["alto"],
        "tipos": ["infraestructura"],
    },
    "hops-high": {
        "nombre": "Saltos excesivos",
        "descripcion": "Nodo originando paquetes con hop_start superior a lo recomendado (6 bajo, >= 7 alto)",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["bajo", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    # --- Reglas de Ampliación Futuras ---
    "battery-drain": {
        "nombre": "Descarga solar acelerada",
        "descripcion": "Router solar con proyección de vaciado en menos de 3 días",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "airtime-high": {
        "nombre": "Uso de tiempo de aire excesivo",
        "descripcion": "Emisiones de tiempo de aire elevadas (> 4% bajo, > 6% medio, > 8% alto)",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["bajo", "medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "gateway-no-traffic": {
        "nombre": "Pasarela sin tráfico LoRa",
        "descripcion": "Pasarela conectada a MQTT pero sin recepciones de radio LoRa durante más de 1 hora",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["bajo"],
        "tipos": ["infraestructura"],
    },
    "key-security": {
        "nombre": "Clave pública insegura o alterada",
        "descripcion": "Detección de claves públicas débiles con baja entropía estructural o cambio inesperado de clave en el mismo nodo",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "router-moving": {
        "nombre": "Router en movimiento",
        "descripcion": "Repetidor o router de infraestructura desplazándose más de 5 km en una ventana de 24 horas",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["alto"],
        "tipos": ["infraestructura"],
    },
    "router-cluster": {
        "nombre": "Concentración de routers contiguos",
        "descripcion": "Router conectado como vecino directo a 3 o más routers simultáneamente",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "asymmetric-link": {
        "nombre": "Enlace RF asimétrico severo",
        "descripcion": "Asimetría severa de SNR (> 6 dB) entre dos nodos de infraestructura o clientes fijos",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "tx-dropped": {
        "nombre": "Descartes de transmisión",
        "descripcion": "Cola de transmisión de router desbordada",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "noise-high": {
        "nombre": "Ruido e interferencia",
        "descripcion": "Suelo de ruido elevado sobre la mediana histórica",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "config-intervals": {
        "nombre": "Intervalos de emisión agresivos",
        "descripcion": "Emisión de telemetría o posición más frecuente de lo recomendado",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["bajo"],
        "tipos": ["infraestructura"],
    },
    "new-node-burst": {
        "nombre": "Ráfaga de nodos nuevos",
        "descripcion": "Aparición masiva de identificadores no vistos previamente",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "mqtt-into-rf": {
        "nombre": "Re-inyección MQTT a radio",
        "descripcion": "Paquetes con bandera via_mqtt oídos por radiofrecuencia",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "ok-to-mqtt-violation": {
        "nombre": "Violación de bit OK-to-MQTT",
        "descripcion": "Gateway subiendo paquetes de nodos que no han dado consentimiento",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "impossible-jump": {
        "nombre": "Desplazamiento inverosímil",
        "descripcion": "Velocidad calculada entre posiciones superior a 300 km/h",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["bajo", "medio"],
        "tipos": ["infraestructura", "clientes"],
    },
    "duplicate-pubkey": {
        "nombre": "Clave pública duplicada",
        "descripcion": "Misma clave pública Meshtastic compartida por distintos IDs",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["alto"],
        "tipos": ["infraestructura"],
    },
    "identity-conflict": {
        "nombre": "Conflicto de identidad",
        "descripcion": "Mismo ID de nodo emitiendo con claves públicas distintas",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
}
