"""Metadatos estáticos y catálogo completo de reglas de supervisión."""

from typing import Any

METADATOS_REGLAS: dict[str, dict[str, Any]] = {
    # --- Reglas MVP ---
    "reboot-loop": {
        "nombre": "Bucle de reinicio",
        "descripcion": "Detección de reinicios continuos en ventana de 60 min",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["bajo", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "battery-low": {
        "nombre": "Batería baja",
        "descripcion": "Nivel de batería crítico confirmado en 2 muestras consecutivas",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["bajo", "medio", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    "infra-silent": {
        "nombre": "Router silente",
        "descripcion": "Router de infraestructura que deja de oírse según su intervalo típico",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura"],
    },
    "gateway-offline": {
        "nombre": "Gateway desconectado",
        "descripcion": "Pasarela que deja de publicar recepciones en el broker MQTT",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura"],
    },
    "flood": {
        "nombre": "Inundación de paquetes",
        "descripcion": "Nodo emitiendo tráfico propio por encima de su ritmo normal",
        "fase": "mvp",
        "afecta_malla": True,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura"],
    },
    "rafaga-masiva": {
        "nombre": "Ráfaga masiva simultánea",
        "descripcion": "Múltiples nodos emitiendo de forma sincronizada en la malla",
        "fase": "mvp",
        "afecta_malla": True,
        "riesgos": ["alto"],
        "tipos": ["infraestructura"],
    },
    "hops-high": {
        "nombre": "Saltos excesivos",
        "descripcion": "Nodo originando paquetes con hop_start superior a lo recomendado (6 bajo, >= 7 alto)",
        "fase": "mvp",
        "afecta_malla": False,
        "riesgos": ["bajo", "alto"],
        "tipos": ["infraestructura", "clientes"],
    },
    # --- Reglas de Ampliación ---
    "battery-drain": {
        "nombre": "Descarga solar acelerada",
        "descripcion": "Router solar con proyección de vaciado en menos de 3 días",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "chutil-high": {
        "nombre": "Canal saturado",
        "descripcion": "Ocupación de canal elevada reportada por un router",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura"],
    },
    "airtime-high": {
        "nombre": "Uso de tiempo de aire excesivo",
        "descripcion": "Emisiones cercanas al límite horario del 10%",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio", "alto"],
        "tipos": ["infraestructura"],
    },
    "tx-dropped": {
        "nombre": "Descartes de transmisión",
        "descripcion": "Cola de transmisión de router desbordada",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "noise-high": {
        "nombre": "Ruido e interferencia",
        "descripcion": "Suelo de ruido elevado sobre la mediana histórica",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "text-flood": {
        "nombre": "Inundación de mensajes de texto",
        "descripcion": "Spam de texto emitido por un nodo",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "config-intervals": {
        "nombre": "Intervalos de emisión agresivos",
        "descripcion": "Emisión de telemetría o posición más frecuente de lo recomendado",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["bajo"],
        "tipos": ["infraestructura"],
    },
    "router-role": {
        "nombre": "Rol de router no coordinado",
        "descripcion": "Nodo con rol de router no listado en la coordinación de malla",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["bajo"],
        "tipos": ["infraestructura"],
    },
    "new-node-burst": {
        "nombre": "Ráfaga de nodos nuevos",
        "descripcion": "Aparición masiva de identificadores no vistos previamente",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "mqtt-into-rf": {
        "nombre": "Re-inyección MQTT a radio",
        "descripcion": "Paquetes con bandera via_mqtt oídos por radiofrecuencia",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "ok-to-mqtt-violation": {
        "nombre": "Violación de bit OK-to-MQTT",
        "descripcion": "Gateway subiendo paquetes de nodos que no han dado consentimiento",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
    "impossible-jump": {
        "nombre": "Desplazamiento inverosímil",
        "descripcion": "Velocidad calculada entre posiciones superior a 300 km/h",
        "fase": "ampliacion",
        "afecta_malla": False,
        "riesgos": ["bajo", "medio"],
        "tipos": ["infraestructura", "clientes"],
    },
    "duplicate-pubkey": {
        "nombre": "Clave pública duplicada",
        "descripcion": "Misma clave pública Meshtastic compartida por distintos IDs",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["alto"],
        "tipos": ["infraestructura"],
    },
    "identity-conflict": {
        "nombre": "Conflicto de identidad",
        "descripcion": "Mismo ID de nodo emitiendo con claves públicas distintas",
        "fase": "ampliacion",
        "afecta_malla": True,
        "riesgos": ["medio"],
        "tipos": ["infraestructura"],
    },
}
